# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers

    working_directory: ~/Python

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --alluredir ~/Python/allure_results_json

      - run:
          name: make report
          command:  |
            allure generate -c /PythonCourse/allure_results_json -o /PythonCourse/allure_results
          when: always

      - store_artifacts:
          path: ~/Python/allure_results
          destination: allure_results
          when: always